### ISSUE TITLE
SMB false positive results. Bug report

### ISSUE THREAD

**Issue by getdrive** [vanhauser-thc/thc-hydra#427] opened 2019-07-02 10:06 UTC
Good day.
By testing our own network for the presence of weak passwords for the SMB protocol, I found that on one of the hosts the hydra 9.0 returns false positive results.
Compared traffic dumps and found the following.
On the host from which we get false positive results, the reply is as follows:

                       SMB PACKET: SMBsesssetupX (REPLY)
                       SMB Command   =  0x73
                       Error class   =  0x5B
                       Error code    =  49152 (0xc000)
                       Flags1        =  0x88
                       Flags2        =  0x1
                       Tree ID       =  0 (0x0)
                       Proc ID       =  14099 (0x3713)
                       UID           =  0 (0x0)
                       MID           =  1 (0x1)
                       Word Count    =  0 (0x0)
                       NTError = STATUS_LOGON_TYPE_NOT_GRANTED
                       smb_bcc=0

In response with normal results:

                       SMB PACKET: SMBsesssetupX (REPLY)
                       SMB Command   =  0x73
                       Error class   =  0x6D
                       Error code    =  49152 (0xc000)
                       Flags1        =  0x88
                       Flags2        =  0x1
                       Tree ID       =  0 (0x0)
                       Proc ID       =  14099 (0x3713)
                       UID           =  0 (0x0)
                       MID           =  1 (0x1)
                       Word Count    =  0 (0x0)
                       NTError = STATUS_LOGON_FAILURE
                       smb_bcc=0

It looks like that the hydra perceives the error code "STATUS_LOGON_TYPE_NOT_GRANTED" as a successful authorization and returns false positive results.
Please check it.
All hosts have Windows 7 Professional SP1 installed.
Command: hydra -L users -P users ip_addres smb -I

**Comment by vanhauser-thc** [comment] 2019-07-02 10:59
can you please add the following switches:  -d -vvv

and paste the full hydra output of one -l -p attempt?
thanks!

**Comment by getdrive** [comment] 2019-07-02 11:38
<details>
<summary><small>Full hydra output</small></summary><p>
hydra -l user -p user 192.168.0.119 smb -I -d -vvv

Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

[DEBUG] Output color flag is 1
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-07-02 14:23:03
[DEBUG] cmdline: hydra -l user -p user -I -d -vvv 192.168.0.119 smb 
[INFO] Reduced number of tasks to 1 (smb does not like parallel connections)
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking smb://192.168.0.119:445/
[VERBOSE] Resolving addresses ... 
[DEBUG] resolving 192.168.0.119
[VERBOSE] resolving done
DEBUG_CONNECT_OK
[DEBUG] Code: attack   Time: 1562066583
[DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service smb
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 5  countpass 1  sizepass 5
[DEBUG] Target 0 - target 192.168.0.119  ip 192.168.0.119  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr user  pass_ptr user
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 3459
[DEBUG] head_no 0 has pid 3459
[VERBOSE] accntFlag is 2
[VERBOSE] hashFlag is 2
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin user, tpass user, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin user, cpass user, tlogin -p, tpass user, redo 0
[ATTEMPT] target 192.168.0.119 - login "user" - pass "user" - 1 of 1 [child 0] (0/0)
DEBUG_CONNECT_OK
[VERBOSE] Attempting WIN2K Native mode.
[DEBUG] SEND [pid:3459] (194 bytes):
0000:  0000 00be ff53 4d42 7200 0000 0008 01c0    [ .....SMBr....... ]
0010:  0000 0000 0000 0000 0000 0000 0000 3b22    [ ..............;" ]
0020:  cdef 0100 009b 0002 5043 204e 4554 574f    [ ........PC NETWO ]
0030:  524b 2050 524f 4752 414d 2031 2e30 0002    [ RK PROGRAM 1.0.. ]
0040:  4d49 4352 4f53 4f46 5420 4e45 5457 4f52    [ MICROSOFT NETWOR ]
0050:  4b53 2031 2e30 3300 024d 4943 524f 534f    [ KS 1.03..MICROSO ]
0060:  4654 204e 4554 574f 524b 5320 332e 3000    [ FT NETWORKS 3.0. ]
0070:  024c 414e 4d41 4e31 2e30 0002 4c4d 312e    [ .LANMAN1.0..LM1. ]
0080:  3258 3030 3200 0244 4f53 204c 414e 4d41    [ 2X002..DOS LANMA ]
0090:  4e32 2e31 0002 4c41 4e4d 414e 322e 3100    [ N2.1..LANMAN2.1. ]
00a0:  0253 616d 6261 0002 4e54 204c 414e 4d41    [ .Samba..NT LANMA ]
00b0:  4e20 312e 3000 024e 5420 4c4d 2030 2e31    [ N 1.0..NT LM 0.1 ]
00c0:  3200                                       [ 2.               ]
[DEBUG] RECV [pid:3459] (113 bytes):
0000:  0000 006d ff53 4d42 7200 0000 0088 01c0    [ ...m.SMBr....... ]
0010:  0000 0000 0000 0000 0000 0000 0000 3b22    [ ..............;" ]
0020:  cdef 0100 1109 0003 3200 0100 0411 0000    [ ........2....... ]
0030:  0000 0100 0000 0000 fce3 0100 9cd1 4b87    [ ..............K. ]
0040:  c830 d501 4cff 0828 00fb 4270 11de b7e6    [ .0..L..(..Bp.... ]
0050:  ca57 004f 0052 004b 0047 0052 004f 0055    [ .W.O.R.K.G.R.O.U ]
0060:  0050 0000 0050 004f 0050 004f 0056 0000    [ .P. C. ]
0070:  00                                         [ .                ]
[VERBOSE] Server requested ENCRYPTED password without security signatures.
[VERBOSE] Server machine name: PC
[VERBOSE] Server primary domain: WORKGROUP
[VERBOSE] Attempting NTLM password authentication.
[DEBUG] UTF8_UTF16LE in:
0000:  7573 6572                                  [ user             ]
[DEBUG] UTF8_UTF16LE out:
0000:  7500 7300 6500 7200                        [ u.s.e.r.         ]
[DEBUG] UTF8_UTF16LE in:
0000:  7573 6572                                  [ user             ]
[DEBUG] UTF8_UTF16LE out:
0000:  7500 7300 6500 7200                        [ u.s.e.r.         ]
[DEBUG] UTF8_UTF16LE in:
[DEBUG] UTF8_UTF16LE out:
[DEBUG] UTF8_UTF16LE in:
0000:  556e 6978                                  [ Unix             ]
[DEBUG] UTF8_UTF16LE out:
0000:  5500 6e00 6900 7800                        [ U.n.i.x.         ]
[DEBUG] UTF8_UTF16LE in:
0000:  5361 6d62 61                               [ Samba            ]
[DEBUG] UTF8_UTF16LE out:
0000:  5300 6100 6d00 6200 6100                   [ S.a.m.b.a.       ]
[VERBOSE] Set NBSS header length: 90
[VERBOSE] Set byte count: 00
[DEBUG] SEND [pid:3459] (148 bytes):
0000:  0000 0090 ff53 4d42 7300 0000 0008 01c0    [ .....SMBs....... ]
0010:  0000 0000 0000 0000 0000 0000 0000 1337    [ ...............7 ]
0020:  0000 0100 0dff 0000 00ff ff02 003c 7d00    [ .............<}. ]
0030:  0000 0018 0018 0000 0000 005c 0000 0053    [ ...........\...S ]
0040:  0000 0000 0000 0000 0000 0000 0000 0000    [ ................ ]
0050:  0000 0000 0000 0000 00ed b776 323f 834d    [ ...........v2?.M ]
0060:  4264 017e 25e4 76c3 a346 21d3 648b e785    [ Bd.~%.v..F!.d... ]
0070:  8000 7500 7300 6500 7200 0000 0000 5500    [ ..u.s.e.r.....U. ]
0080:  6e00 6900 7800 0000 5300 6100 6d00 6200    [ n.i.x...S.a.m.b. ]
0090:  6100 0000                                  [ a...             ]
[DEBUG] RECV [pid:3459] (39 bytes):
0000:  0000 0023 ff53 4d42 735b 0100 c088 01c0    [ ...#.SMBs[...... ]
0010:  0000 0000 0000 0000 0000 0000 0000 1337    [ ...............7 ]
0020:  0000 0100 0000 00                          [ .......          ]
[VERBOSE] SMBSessionRet: 0000015B SMBerr: 015B SMBaction: 00
[VERBOSE] Valid password, GPO Deny access to this computer from the network
[DEBUG] head_no[0] read F
[445][smb] host: 192.168.0.119   login: user   password: user
DEBUG_DISCONNECT
[DEBUG] head_no[0] read n
[STATUS] attack finished for 192.168.0.119 (waiting for children to complete tests)
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] all targets done and all heads finished
[DEBUG] while loop left with 1
1 of 1 target successfully completed, 1 valid password found
[DEBUG] killing all remaining children now that might be stuck
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-07-02 14:23:03
</p></details>

**Comment by vanhauser-thc** [comment] 2019-07-02 19:59
Hydra states: "[VERBOSE] Valid password, GPO Deny access to this computer from the network"

so the password is valid. however I cannot use it to login.

if hydra would say its a bad password it would continue trying which is the wrong thing  - as the password was found.

But what is the issue is that this message is only in verbose mode. I will change that.

thanks for reporting!

**Comment by vanhauser-thc** [comment] 2019-07-02 20:05
fix is in the repository

**Closed** 2019-07-03 02:02 UTC
