### ISSUE TITLE
repology.org | Problems in Wikidata

### ISSUE THREAD

**Issue by Ricky-Tigg** [vanhauser-thc/thc-hydra#764] opened 2022-06-09 08:37 UTC
Hello. In its current configuration, [Repology](https://repology.org/), an on-line service aimed to be a packaging hub, gets its information associated to packages from a unique source – [Wikidata](https://www.wikidata.org). Thus that very dependency makes it unreliable, as the information it gathers can at best be as in-accurate as the one that is present in that source. As a consequence, are present there package versions having been **assigned wrong label colour codes**.

_legend | label colour codes involved in issue_

![repology org_label_colour_codes](https://user-images.githubusercontent.com/26058215/172784115-ccb46888-2310-4961-8fb8-37b212475e91.png)

The component _[secure-delete](https://repology.org/project/secure-delete/versions)_ currently [illustrates](https://repology.org/projects/?search=secure-delete&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=) that case. Its maintenance takes place at [page](https://www.wikidata.org/wiki/Q65932042). Components whose definitions are erroneous are [reported](https://repology.org/repository/wikidata/problems).

**Comment by Ricky-Tigg** [comment] 2022-06-09 13:44
The issue, reported as "_Homepage link http://shutter-project.org/ is a permanent redirect to its HTTPS counterpart https://shutter-project.org/ and should be updated._", might be the cause of wrong label assignments.


"

**Comment by vanhauser-thc** [comment] 2022-06-09 17:23
and what do we have to do with shutter-project either?

**Comment by Ricky-Tigg** [comment] 2022-06-10 07:46
Nothing of course, since it did make no doubt that is could be nothing but an **erroneous** illustration, as you could have noticed it by yourself. FTR, you don't need me to read the relevant string there, which was "_Homepage link http://www.thc.org/releases.php is [dead](https://repology.org/link/http://www.thc.org/releases.php) (HTTP 404) for more than a month and should be replaced by alive link (or link to [archive.org](https://archive.org/) as a last resort)._"

**Comment by vanhauser-thc** [comment] 2022-06-12 06:29
if you want to help then fix broken links in other websites rather putting the effort to report that e.g. here and me not knowing what the issue is, how to fix it and why that would be useful to fix - and then maybe me taking the time to fix this ... when fixing this by the reporter would have saved everybody a lot of time :)
(I still dont understand why this should be fixed, or how, and what the benefit would be)

**Closed by vanhauser-thc** 2022-06-12 06:29 UTC
