### ISSUE TITLE
High percentage CPU use and hydra stuck while hydra crack ssh logons with higher threads 

### ISSUE THREAD

**Issue by sunjysun** [vanhauser-thc/thc-hydra#113] opened 2016-05-04 10:52 UTC
High percentage CPU use and hydra stuck at [REDO-ATTEMPT] while hydra crack ssh logons with higher threads (somtimes about 13 or more)
![2016-05-04 18-47-46](https://cloud.githubusercontent.com/assets/11803512/15012149/f0bedcf6-1228-11e6-9ec9-3c52c01cc707.png)
And after waiting a long time, new line shows "[Status] ...many many to do in many many hours"

**Comment by vanhauser-thc** [comment] 2016-05-10 07:28
many things.

first, there seems to be a bug in the status calculations. but I have never seen that before.

second, you are running way too many parallel attacks. you see the many redos, protocol errors, etc - the server does not allow that many. hydra can handle that, but you see the CPU load. you are basically running 32+1 processes against the target. try 8. (-t 8)

**Comment by vanhauser-thc** [comment] 2016-06-15 18:09
I added a patch to hydra which will terminate and report if the status calculation bug happens.
please post here the command line when this is triggered plus the OS and if its 32bit or 64bit.

**Comment by meitar** [comment] 2016-06-15 20:43
I received this ERROR message while testing Hydra today:

```
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org
```

The command line I used was this:

```
./hydra -l admin -p password -vV -d -f -W 5 -t 1 -o /tmp/hydra-debug.out www.myserver123.com https-post-form "/wp-login.php:log=^USER^&pwd=^PASS^:incorrect"
```

This was my own hydra running on 64-bit Linux and compiled from commit 9a90a24a4962b7d89b4ae89ba98697d9d9d79eaa, not a distribution's packaged copy.

**Comment by vanhauser-thc** [comment] 2016-06-15 21:12
I tried it on 64bit Cygwin, and 32 and 64 bit Linux - did not happen here.

So it must be something that happends because of what the server is sending and how hydra is reacting to that.

Can you either please send the full debug output or reveal the destination server (e.g. via email to me)?

**Comment by meitar** [comment] 2016-06-15 22:31
@vanhauser-thc Yeah, I'll email you. I'll use PGP key with fingerprint `9306 0EA4 76F3 9C79 11CC  535D 5767 7A05 A8C1 A61D`.

**Comment by sboutzen** [comment] 2016-06-20 21:07
Im having the same issue, commandline: `./hydra 192.168.56.101 http-form-post "/intra/:username=^USER^&password=^PASS^:Please login" -l jvirtane -P ../Desktop/passwords_list.lst -t 1 -o hydra_hackz.txt -V` 64 bit kali VM in VirtualBox

**Comment by vanhauser-thc** [comment] 2016-06-21 07:49
@sboutzen does this happen with the current github version? if yes, can you please send a full screen output with -d option enabled? thanks!

**Comment by sboutzen** [comment] 2016-06-21 08:13
I was using the current github version yes. I also tried version 5.9, couldn't get that to work (my mistake, not hydras), and when I tried with the github version again, it just worked. I have no clue what happened, and I did not take a screen shot of the error when I got it :/

**Comment by vanhauser-thc** [comment] 2016-06-21 08:32
@sboutzen you could run the command via a script like 100 times, log the output individually away and see if it occurs again :)  (I would restrict the password list to 5-10 entries though).

**Comment by Cabalist** [comment] 2016-06-22 22:22
On OS X 10.11.5.  Hydra v8.3-dev
```
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org
```

``` hydra -l admin -P rockyou.txt 192.168.1.1 http-head```

The only odd things were the router was unplugged for a little bit and the computer was put to sleep a couple of times.

**Comment by vanhauser-thc** [comment] 2016-06-23 06:54
@Cabalist 

can you try to reproduce it? that would really help. please add the options "-d -t 1" and send the full output.

**Comment by Cabalist** [comment] 2016-06-24 06:46
I've been working on it and I have been unable to reproduce it using smaller lists.  I'll keep bumping it up and see if I get something for you.  

Rockyou is 14,344,391 entries.  I've done all the way up to 100,000 without seeing the issue again.

**Comment by vanhauser-thc** [comment] 2016-07-05 18:26
Hi guys,

I hope it is fixed - can you please retry with the current github state?

**Comment by Destrocto01** [comment] 2016-07-14 21:04
When I run the command :  hydra -l user -P password.txt "IP ADDRESS" ssh

I got the message :  [ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

Any idea ?

**Comment by vanhauser-thc** [comment] 2016-07-15 07:02
@Destrocto01 this should have been fixed in this github archive 10 days ago. did you compile from before or after that?

**Comment by tonymontana111** [comment] 2016-08-14 15:32
I got the same issu as above. Anyone has some idea how to fix it?

Hydra (http://www.thc.org/thc-hydra) starting at 2016-08-14 17:14:45
[DATA] max 16 tasks per 1 server, overall 64 tasks, 4248 login tries (l:1/p:4248), ~4 tries per task
[DATA] attacking service ftp on port 21
[STATUS] 78.00 tries/min, 78 tries in 00:01h, 4170 to do in 00:54h, 16 active
[STATUS] 78.00 tries/min, 234 tries in 00:03h, 4014 to do in 00:52h, 16 active
[STATUS] 75.43 tries/min, 528 tries in 00:07h, 3720 to do in 00:50h, 16 active
[STATUS] 75.33 tries/min, 1130 tries in 00:15h, 3118 to do in 00:42h, 16 active
[STATUS] 76.00 tries/min, 2356 tries in 00:31h, 1892 to do in 00:25h, 16 active
[STATUS] 76.74 tries/min, 3607 tries in 00:47h, 641 to do in 00:09h, 16 active
[STATUS] 76.90 tries/min, 3999 tries in 00:52h, 249 to do in 00:04h, 16 active
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by vanhauser-thc** [comment] 2016-08-14 20:53
@tonymontana111 and everyone else: update to v8.3

**Comment by tonymontana111** [comment] 2016-08-18 18:04
@vanhauser-thc  could you tell me what i have to update ? Thc-hydra or  whole kali rolling?

**Comment by vanhauser-thc** [comment] 2016-08-19 08:27
@tonymontana111 checkout the github archive here and compile it.
or download from here: http://www.thc.org/releases/hydra-8.3.tar.gz
kali 2.0 is on v8.1 and kali rollin gon v8.2. it is fixed in v8.3 ...

**Comment by vyaradaikin** [comment] 2016-09-20 09:48
ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org-t 
hydra -s 22 -V -l root -P /root/password.txt -t X.X.X.X ssh

**Comment by vanhauser-thc** [comment] 2016-09-20 10:11
Update to 8.3 or use the github version

**Closed by vanhauser-thc** 2016-09-20 10:11 UTC

**Comment by Vazonezzz** [comment] 2016-10-01 16:36
Sorry, I also has the problem, problems, in hydra ERROR] Weird bug detected where more tests were performed than possible. In WPscan The remote site is up, but does not seem running WPscan. In SQLmap also has problem... I don't know what to do else with the site. I need user and pass of the site and tried everything, but... Please help me. Pleeease. Site is Wordpress

**Comment by Cabalist** [comment] 2016-10-02 23:17
@Vazonezzz Have you read this thread?

**Comment by layyetko** [comment] 2017-02-02 00:59
how to update hydra

**Comment by vanhauser-thc** [comment] 2017-02-02 08:26
clone the repository here and compile:

git clone https://github.com/vanhauser-thc/thc-hydra
cd thc-hydra
./configure
make
make install

if any commands fail you have no installed git or a gcc compiler and build tools. if you can not use the Internet find out how to install them you do not deserve to use hydra :p

**Comment by KFayal** [comment] 2017-03-06 03:27
My command line was hydra -l root -P password-list.txt 10.11.1.8 ssh

**Comment by johnwmintz** [comment] 2017-04-30 16:15
I had this error when I was running against SickOS1.2 from VulnHub.  My password list is 1000 top passwords.  
root@kali:~/Desktop/SickOS1.2# hydra -l root -P 1000.txt 192.168.226.130 ssh
Hydra v8.2 (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-04-30 11:11:50
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[WARNING] Restorefile (./hydra.restore) from a previous session found, to prevent overwriting, you have 10 seconds to abort...
[DATA] max 16 tasks per 1 server, overall 64 tasks, 1000 login tries (l:1/p:1000), ~0 tries per task
[DATA] attacking service ssh on port 22
[STATUS] 909.00 tries/min, 909 tries in 00:01h, 91 to do in 00:01h, 16 active
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by vanhauser-thc** [comment] 2017-04-30 17:27
as stated here: update to to the newest version or use the github version

**Comment by anton-kulik** [comment] 2017-12-17 19:57
I received this error message while testing Hydra today:
`[ERROR] Weird bug detected where more tests were performed than possible.`
My system: CentOS Linux release 7.4.1708 (Core), Linux 3.10.0-693.11.1.el7.x86_64
Hydra version: Hydra v8.2-dev
Command line:
`hydra -L logins.txt -P pass.txt -M rdpip.txt -o hydra_res.txt -t 64 -F -v -V rdp`
Thanx.

**Comment by vanhauser-thc** [comment] 2017-12-18 10:41
@anton-kulik update to the newest version

**Comment by lanhhuyet510** [comment] 2018-01-31 10:08
![image](https://user-images.githubusercontent.com/11714075/35616936-51a9cd34-06a9-11e8-8f7b-62b9d04dc930.png)
hydra -f -l root -P john.txt rdp://127.0.0.1

**Comment by ertanuj96** [comment] 2018-10-17 17:45
hello , I also having this issue when I was cracking a online web form , that allows users to print their result card , my password file total count  was 2976 but hydra attempted 2980 passwords to crack web form , at last I was shown the same error as in upper comments encountered by other testers.

**Comment by ertanuj96** [comment] 2018-10-17 17:46
[ATTEMPT] target 164.100.118.41 - login "507104146" - pass "31/12/1997" - 2972 of 3105 [child 6]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[ATTEMPT] target 164.100.118.41 - login "507104146" - pass "31/12/1998" - 2973 of 3105 [child 14]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[ATTEMPT] target 164.100.118.41 - login "507104146" - pass "31/12/1999" - 2974 of 3105 [child 11]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[ATTEMPT] target 164.100.118.41 - login "507104146" - pass "31/12/2000" - 2975 of 3105 [child 12]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[ATTEMPT] target 164.100.118.41 - login "507104146" - pass "31/12/2001" - 2976 of 3105 [child 0]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[REDO-ATTEMPT] target 164.100.118.41 - login "507104146" - pass "01/01/1996" - 2977 of 3105 [child 7]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[REDO-ATTEMPT] target 164.100.118.41 - login "507104146" - pass "01/01/1997" - 2978 of 3105 [child 3]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[REDO-ATTEMPT] target 164.100.118.41 - login "507104146" - pass "01/01/1998" - 2979 of 3105 [child 1]
[ERROR] Not an Asterisk Call Manager protocol or service shutdown: (null)
[REDO-ATTEMPT] target 164.100.118.41 - login "507104146" - pass "01/01/1999" - 2980 of 3105 [child 8]
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by ertanuj96** [comment] 2018-10-17 17:49
this is  the output file 
[xhydrabugoutput.txt](https://github.com/vanhauser-thc/thc-hydra/files/2488604/xhydrabugoutput.txt)

**Comment by vanhauser-thc** [comment] 2018-10-19 06:31
@ertanuj96 you are using a very old version. please clone the github repository, compile it and retry with this one. ensure that you are using the github one by typing "hydra -h" and checking the version ;)

**Comment by josephmatt18** [comment] 2022-09-22 17:03
Was told to post this here

`[user@centos7 Downloads]$ hydra -l vastdata -P rockyou.txt x.x.x.x -t 64 ssh 
Hydra v8.2-dev (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2022-09-22 12:03:05
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[WARNING] Restorefile (./hydra.restore) from a previous session found, to prevent overwriting, you have 10 seconds to abort...
[DATA] max 64 tasks per 1 server, overall 64 tasks, 12670 login tries (l:1/p:12670), ~3 tries per task
[DATA] attacking service ssh on port 22
[STATUS] 1269.00 tries/min, 1269 tries in 00:01h, 11401 to do in 00:09h, 64 active
[STATUS] 1162.00 tries/min, 3486 tries in 00:03h, 9184 to do in 00:08h, 64 active
[STATUS] 1108.86 tries/min, 7762 tries in 00:07h, 4908 to do in 00:05h, 64 active
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org`

**Comment by vanhauser-thc** [comment] 2022-09-26 01:56
@josephmatt18 why are you using an outdated version from many years ago?

**Comment by vanhauser-thc** [comment] 2022-09-27 11:10
your distro ships an outdated hydra ... you will have to compile it yourself

**Comment by josephmatt18** [comment] 2022-09-27 18:53
@vanhauser-thc  - Sounds good, will do.... thank you!
