### ISSUE TITLE
https-post-form cuts argument length to ~ 1000 symbols

### ISSUE THREAD

**Issue by klensy** [vanhauser-thc/thc-hydra#192] opened 2017-02-19 15:29 UTC
Hello.

hydra v8.4

If we pass very long argument line to https-post-form, hydra cuts total length to ~ 1000 symbols. Counts all symbols inside quotes: https-post-form "**there**"

$ hydra -l my_user -p my_pass -S example.com https-post-form "/some/path/:login=^USER^&pass=^PASS^:error:H=Cookie\\: very_long_cookie_to_exceed_total_argument_length_over_1000_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

**Comment by vanhauser-thc** [comment] 2017-02-21 18:44
hmmm I will look into it.
Sure its possible, but due to the code complexity it is not easy and one or two line of changes.

**Comment by vanhauser-thc** [comment] 2017-02-23 20:26
how long would you need the string to be?

**Comment by klensy** [comment] 2017-02-23 20:42
This should be enough (corner case): max cookie size (4096 bytes) + max url size (about 2000 chars, so, for simplicity count as ascii chars). So, 6096 bytes ought to be enough for anybody.

**Comment by euphrat1ca** [comment] 2017-02-27 08:19
well,hello. i'm new to this security-tools. Is there someone could tell me how to Convert source code to the windows.  I used the Cygwin with the guide from the internet. But it still have some error.
like this :   terminals database is inaccessible

**Comment by vanhauser-thc** [comment] 2017-02-27 09:41
@euphrat1ca this is not a help forum but solely for reporting bugs in the software.

**Comment by klensy** [comment] 2017-03-10 09:24
Any progress?

**Comment by vanhauser-thc** [comment] 2017-03-10 11:32
no time so far. feel free to supply a patch of your own if you have the time and skill

**Comment by petrock6** [comment] 2017-05-20 05:57
I've updated the code to support the max URL, and POST/cookie data size to 6096 bytes. I've emailed vanhauser-thc about this, since I may need some assistance regarding a pull request to the main repo. 

Unfortunately, I cannot attach the code here, and I'm inexperienced with open source development on github so I'm not exactly sure as to how I can submit this code.

**Comment by vanhauser-thc** [comment] 2017-05-20 13:46
included patch, should now allow for 6000 bytes

**Comment by tjgerot** [comment] 2017-05-26 04:32
Can confirm the issue is fixed on master (version 8.6-dev). See #218.

**Closed** 2017-05-26 07:15 UTC
